### ISSUE TITLE
Very good work. Can we get the same area in two images according to the image registration result? Have the corresponding code?

### ISSUE THREAD

**Issue by 1zgh** [ACuOoOoO/ReDFeat#1]
Very good work. Can we get the same area in two images according to the image registration result? Have the corresponding code?

**Comment by ACuOoOoO** [comment]
Does the same area mean the overlap region? If true, you can estimate the homography matrix and then warp a white picture to obtain the overlap mask.

**Comment by ACuOoOoO** [comment]
> Very good work. Can we get the same area in two images according to the image registration result? Have the corresponding code?

Does the same area mean the overlap region? If true, you can estimate the homography matrix and then warp a white picture to obtain the overlap mask.
