### ISSUE TITLE
dataset.py的代码中是否有错误呢？

### ISSUE THREAD

**Issue by 654hhh** [ACuOoOoO/ReDFeat#2]
class MMDataset(Dataset):
    def __init__(self,path,type,transform=None,crop_size=192):
        # fh = open(txt, 'r')
        path0=os.path.join(path,type,'train',type.split('_')[0])
        path1=os.path.join(path,type,'train',type.split('_')[1])
        pathDir = os.listdir(path0)
        imgs0 = []
        imgs1 = []
        for i in range(len(pathDir)):
            imgs0.append(path0+'/'+pathDir[i])
            imgs1.append(path1+'/'+pathDir[i])
 请问在上述代码中，是不是没有正确的得到path1路径下(红外)下的图片？

**Comment by ACuOoOoO** [comment]
假如type是VIS_IR，则可以读取以下路径的图片
 └── path
        └── VIS
                ├── img0
                ├── img1
        └── IR
                ├── img0
                ├── img1
