### ISSUE TITLE
重复训练结果不一致

### ISSUE THREAD

**Issue by huhulike** [ACuOoOoO/ReDFeat#3]
非常好的工作，但是我用了相同参数重复训练几次，每次结果都不一样，而且相差三四个点，请问作者有没有出现过这个问题？

**Comment by ACuOoOoO** [comment]
请问是哪种数据，哪个指标复现有问题？

**Comment by ACuOoOoO** [comment]
> 非常好的工作，但是我用了相同参数重复训练几次，每次结果都不一样，而且相差三四个点，请问作者有没有出现过这个问题？

请问是哪种数据，哪个指标复现有问题？

**Comment by huhulike** [comment]
VIS_IR数据集，RR和MS指标

**Comment by huhulike** [comment]
> > 非常好的工作，但是我用了相同参数重复训练几次，每次结果都不一样，而且相差三四个点，请问作者有没有出现过这个问题？
> 
> 请问是哪种数据，哪个指标复现有问题？

VIS_IR数据集，RR和MS指标

**Comment by ACuOoOoO** [comment]
> > > 非常好的工作，但是我用了相同参数重复训练几次，每次结果都不一样，而且相差三四个点，请问作者有没有出现过这个问题？
> > 
> > 
> > 请问是哪种数据，哪个指标复现有问题？
> 
> VIS_IR数据集，RR和MS指标

经过50个epochs重新训练所得模型在VIS-IR上所提取1024点的RR为38.89，MS为15.3，与公布模型的38.13和15.3接近。2048点结果接近。4096点有所差异较大，但不显著（小于三个点）。

请根据最新更新的特征提取和测试代码再次进行测试，如有问题，欢迎提问。

**Comment by huhulike** [comment]
> > > > 非常好的工作，但是我用了相同参数重复训练几次，每次结果都不一样，而且相差三四个点，请问作者有没有出现过这个问题？
> > > 
> > > 
> > > 请问是哪种数据，哪个指标复现有问题？
> > 
> > 
> > VIS_IR数据集，RR和MS指标
> 
> 经过50个epochs重新训练所得模型在VIS-IR上所提取1024点的RR为38.89，MS为15.3，与公布模型的38.13和15.3接近。2048点结果接近。4096点有所差异较大，但不显著（小于三个点）。
> 
> 请根据最新更新的特征提取和测试代码再次进行测试，如有问题，欢迎提问。

收到，谢谢，感谢你的回复，也再次感谢你的工作！！
