### ISSUE TITLE
Test results on the VIS_NIR dataset differ significantly from the results reported in the paper.

### ISSUE THREAD

**Issue by lyp-deeplearning** [ACuOoOoO/ReDFeat#4]
Thank you for providing excellent work and test datasets. However, I have a question: whether I use the provided pre-trained model or the re-trained model, I cannot achieve the results reported in the paper on the VIS_NIR subset. In Fig.6 of the paper, it shows that on VIS_NIR, with 1024, 2048, and 4096 keypoints, the matching scores are 0.38, 0.39, and 0.4, respectively.

My reproduce result is 0.32,0.31,0.28:
`Number of infrared keypoints: 1024.000000.
Number of visible keypoints: 1024.000000.
Number of correspondence: 415.878788.
Number of correct matches: 312.439394.
RR: 0.4061316287878788.
MS: 0.3232935243350404.
[Warning] Log file already exists.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 132/132 [02:30<00:00,  1.14s/it]
Number of infrared keypoints: 2048.000000.
Number of visible keypoints: 2048.000000.
Number of correspondence: 840.371212.
Number of correct matches: 604.325758.
RR: 0.4103375059185606.
MS: 0.31349282916117693.
[Warning] Log file already exists.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 132/132 [09:41<00:00,  4.41s/it]
Number of infrared keypoints: 4068.212121.
Number of visible keypoints: 4062.265152.
Number of correspondence: 1638.257576.
Number of correct matches: 1071.189394.
RR: 0.40676188417684933.
MS: 0.2806243405662737.`

**Comment by ACuOoOoO** [comment]
> Thank you for providing excellent work and test datasets. However, I have a question: whether I use the provided pre-trained model or the re-trained model, I cannot achieve the results reported in the paper on the VIS_NIR subset. In Fig.6 of the paper, it shows that on VIS_NIR, with 1024, 2048, and 4096 keypoints, the matching scores are 0.38, 0.39, and 0.4, respectively.
> 
> My reproduce result is 0.32,0.31,0.28: `Number of infrared keypoints: 1024.000000. Number of visible keypoints: 1024.000000. Number of correspondence: 415.878788. Number of correct matches: 312.439394. RR: 0.4061316287878788. MS: 0.3232935243350404. [Warning] Log file already exists. 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 132/132 [02:30<00:00, 1.14s/it] Number of infrared keypoints: 2048.000000. Number of visible keypoints: 2048.000000. Number of correspondence: 840.371212. Number of correct matches: 604.325758. RR: 0.4103375059185606. MS: 0.31349282916117693. [Warning] Log file already exists. 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 132/132 [09:41<00:00, 4.41s/it] Number of infrared keypoints: 4068.212121. Number of visible keypoints: 4062.265152. Number of correspondence: 1638.257576. Number of correct matches: 1071.189394. RR: 0.40676188417684933. MS: 0.2806243405662737.`

Hello. Thanks for your attention on our work. Please set min-size at Line 130 in extract.py from 256 to 512 for reproducing the results on VIS-NIR.

**Comment by lyp-deeplearning** [comment]
Thanks for your reply. I have change the min-size to 512, but get the error:
Traceback (most recent call last):
  File "/home/yepeng_liu/code_python/multimodal_remote/dataset/Multimodal_Feature_Evaluation/extract_ReDFeat.py", line 181, in <module>
    xys, desc, scores = extract_multiscale(net, img, detector, '1',
  File "/home/yepeng_liu/code_python/multimodal_remote/dataset/Multimodal_Feature_Evaluation/extract_ReDFeat.py", line 114, in extract_multiscale
    Y = torch.cat(Y)
RuntimeError: torch.cat(): expected a non-empty list of Tensors

If i change the min-size to 500, the extracting script can run normal and get the matching  score of 0.35. However, it still falls short of the 0.4 reported in the paper. Are there any other parameters that need to be adjusted?

**Comment by ACuOoOoO** [comment]
> Thanks for your reply. I have change the min-size to 512, but get the error: Traceback (most recent call last): File "/home/yepeng_liu/code_python/multimodal_remote/dataset/Multimodal_Feature_Evaluation/extract_ReDFeat.py", line 181, in xys, desc, scores = extract_multiscale(net, img, detector, '1', File "/home/yepeng_liu/code_python/multimodal_remote/dataset/Multimodal_Feature_Evaluation/extract_ReDFeat.py", line 114, in extract_multiscale Y = torch.cat(Y) RuntimeError: torch.cat(): expected a non-empty list of Tensors
> 
> If i change the min-size to 500, the extracting script can run normal and get the matching score of 0.35. However, it still falls short of the 0.4 reported in the paper. Are there any other parameters that need to be adjusted?

Please try again with min-size of 512 and max-size of 2048.  It should produce MS: 37.5@1024, 39.0@2048, 39.7@4096.

**Comment by lyp-deeplearning** [comment]
Thanks, i have got the same result as yours. I will close the question.
