### ISSUE TITLE
 The difference in the reproduced OPT-IR results is significant.

### ISSUE THREAD

**Issue by lyp-deeplearning** [ACuOoOoO/ReDFeat#6]
I tested the results of RedFeat on the IR test set using the default settings, with min_size set to 256 and max_size set to 1024. However, I found that the success rate (SR) showed a significant deviation, with only 32 images registered successfully, while the paper reports around 46 successful registrations. Here are the results:
`#successfully repojected image: 32.0
reprojection error is 3.061345286815741 with 1024 points
failed ids: ['19.png', '24.png', '26.png', '31.png', '4.png', '40.png', '41.png', '42.png', '43.png', '44.png', '45.png', '46.png', '48.png', '49.png', '9.png']`

The discrepancy in the results is likely due to the settings. I am very much looking forward to your response.

**Comment by ACuOoOoO** [comment]
@lyp-deeplearning The VIS-IR subset has been updated. Please try again.

**Comment by lyp-deeplearning** [comment]
Thanks for your reply!
